### ISSUE TITLE
Error creating text box form element

### ISSUE THREAD

**Issue by Heyula** [XoopsModules25x/xforms#3]
Error creating text box form element
![1](https://user-images.githubusercontent.com/5504159/128697738-9958ee57-ddd6-41a9-a37f-83573b7fde7b.jpg)
![2](https://user-images.githubusercontent.com/5504159/128697740-1e0901c6-8e35-4973-a435-378d3f36e5f5.jpg)

**Comment by mambax7** [comment]
Thanks! 

Please change line 60 in \xforms\admin\elements\ele_text.php
from: $oUser         `= $memberHelper->createUser();`
to: $oUser         `= $memberHandler->createUser();`

**Comment by aquasquale** [comment]
Hello,
Having the same problem, I just made the modification in the file in \xforms\admin\elements\ele_text.php
but the problem persists 

Only text box, for everything else seems functional

with XOOPS 2.5.11-Beta2
