### ISSUE TITLE
Check box and Text box

### ISSUE THREAD

**Issue by Heyula** [XoopsModules25x/xforms#4]
XOOPS 2.5.11-Beta2

![1](https://user-images.githubusercontent.com/5504159/135850571-29ae7e7b-7dcc-499a-a8f5-3a2b4a7219e8.jpg)
A new field is not added 
-------------------------------------------------------------------------------------------------------------------------
![2](https://user-images.githubusercontent.com/5504159/135850661-a8582d37-f24b-4fe1-a607-fab431ab7a74.jpg)
Text box - gives an error when clicking

**Comment by ggoffy** [comment]
can you please test: https://github.com/ggoffy/xforms

**Comment by Heyula** [comment]
hi @ggoffy 

When I say add a new field, it does not give an error, but the new field is not added.

**Comment by ggoffy** [comment]
can you please test: https://github.com/ggoffy/xforms

**Comment by Heyula** [comment]
hi @ggoffy

thanks it works now.

**Comment by ggoffy** [comment]
👍
